  
name: Metrics

on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]} 

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # Metrics.svg
      - uses: lowlighter/metrics@latest
        name: Skyline
        with:
          plugin_skyline: yes
          plugin_skyline_year: 2021      
          plugin_skyline_frames: 60       
          plugin_skyline_quality: 1   
          plugin_skyline_compatibility: yes # Supports Firefox and Safari
          token: ${{ secrets.METRICS }}
